name: Main

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: Install dependencies
        run: go get .

      - name: Test with Go
        run: go test -coverprofile=coverage.txt -covermode=atomic -json > TestResults.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: TestResults.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3